"""
Rules engine — six checks, pure pandas, no ML.

Every rule here is something an auditor already knows to look for. That's
deliberate: rules should be *explainable to a non-technical person in one
sentence*, and *high recall* — catch generously, let Day 4's anomaly model and
Day 5's graph layer narrow the list down. A rules engine that tries to be
precise on its own is solving the wrong problem.

Each function returns a dict: {tender_id: reason_string}. Reasons are plain
English on purpose — this is the first draft of what Day 8's LLM narration
will eventually polish, and it costs nothing to write them now.
"""

import numpy as np
import pandas as pd

from . import config as C

R = C.RULE_THRESHOLDS


# ═══════════════════════════════════════════════════════ 1. PO SPLITTING
def rule_po_splitting(tenders: pd.DataFrame) -> dict:
    """
    Same vendor, same buyer, several POs close together in time, each sitting
    just under the approval limit, summing to well over it. The oldest trick
    in procurement.
    """
    df = tenders.copy()
    df["award_date"] = pd.to_datetime(df["award_date"])
    reasons = {}

    for (vid, eid), g in df.groupby(["vendor_id", "employee_id"]):
        g = g.sort_values("award_date").reset_index(drop=True)
        for i in range(len(g)):
            limit = g.loc[i, "approval_limit"]
            lo, hi = g.loc[i, "award_date"] - pd.Timedelta(days=R["split_window_days"]), \
                     g.loc[i, "award_date"] + pd.Timedelta(days=R["split_window_days"])
            nearby = g[(g["award_date"] >= lo) & (g["award_date"] <= hi)]
            hugging = nearby[(nearby["amount"] >= R["split_hug_ratio"] * limit) &
                             (nearby["amount"] < limit)]
            if len(hugging) >= 2 and hugging["amount"].sum() > limit:
                for _, row in hugging.iterrows():
                    reasons[row["tender_id"]] = (
                        f"{len(hugging)} POs to the same vendor within "
                        f"{R['split_window_days']} days, each under the "
                        f"${limit:,.0f} approval limit, summing to "
                        f"${hugging['amount'].sum():,.0f}")
    return reasons


# ═════════════════════════════════════════════════════ 2. DUPLICATE INVOICE
def rule_duplicate_invoice(tenders: pd.DataFrame) -> dict:
    """Same vendor billing the same amount twice within a couple of months."""
    df = tenders.copy()
    df["invoice_date"] = pd.to_datetime(df["invoice_date"])
    reasons = {}

    for vid, g in df.groupby("vendor_id"):
        g = g.sort_values("invoice_date").reset_index(drop=True)
        for i in range(len(g)):
            for j in range(i + 1, len(g)):
                gap = (g.loc[j, "invoice_date"] - g.loc[i, "invoice_date"]).days
                if gap > R["dup_window_days"]:
                    break
                if abs(g.loc[j, "amount"] - g.loc[i, "amount"]) <= \
                        R["dup_amount_tolerance"] * g.loc[i, "amount"]:
                    # Flag only the LATER invoice. The first bill was legitimate;
                    # the second is the one that took money out of the door, and
                    # it is the only one ground truth calls fraud. Flagging both
                    # halves of every pair manufactures a false positive for
                    # every true positive. The earlier invoice is still named in
                    # the reason, so the auditor sees both sides of the pair.
                    reasons[g.loc[j, "tender_id"]] = (
                        f"Same vendor billed ${g.loc[i,'amount']:,.0f} "
                        f"twice, {gap} days apart "
                        f"(invoices {g.loc[i,'invoice_id']} / {g.loc[j,'invoice_id']})")
    return reasons


# ═══════════════════════════════════════════════ 3. THIN COMPETITION
def rule_thin_competition(tenders: pd.DataFrame) -> dict:
    """A large purchase awarded with one or two bidders. Legal, but worth a look."""
    hits = tenders[(tenders["n_bidders"] <= R["thin_competition_max_bid"]) &
                   (tenders["amount"] >= R["thin_competition_min_amt"])]
    return {
        row["tender_id"]: (
            f"${row['amount']:,.0f} awarded via {row['award_method']} "
            f"with only {row['n_bidders']} bidder(s)")
        for _, row in hits.iterrows()
    }


# ═════════════════════════════════ 4. ROUND NUMBER NEAR THE THRESHOLD
def rule_round_near_threshold(tenders: pd.DataFrame) -> dict:
    """
    Fabricated amounts tend to be round. A round number that also happens to
    sit just under the approval ceiling is the classic fingerprint of a
    number picked by a person, not generated by a transaction.
    """
    is_round = tenders["amount"] % R["round_to"] == 0
    near_limit = (tenders["amount"] < tenders["approval_limit"]) & \
                 (tenders["amount"] >= tenders["approval_limit"] * (1 - R["round_proximity"]))
    hits = tenders[is_round & near_limit]
    return {
        row["tender_id"]: (
            f"${row['amount']:,.0f} is a round number sitting within "
            f"{R['round_proximity']:.0%} of the ${row['approval_limit']:,.0f} limit")
        for _, row in hits.iterrows()
    }


# ═══════════════════════════════════════ 5. VENDOR CONCENTRATION
def rule_vendor_concentration(tenders: pd.DataFrame) -> dict:
    """
    One vendor taking an outsized share of a single buyer's spend. Normal
    vendors compete for a slice of a buyer's business; a vendor that *is* the
    buyer's business is a relationship worth explaining.
    """
    df = tenders.copy()

    # Direction matters. Asking "what share of this BUYER's spend went to one
    # vendor?" separates nothing — a buyer runs 50 tenders, so no single vendor
    # is ever a large slice. Ask it from the vendor's side instead: "what share
    # of this VENDOR's work came from one buyer?" A ghost vendor scores 1.00 by
    # construction. A colluding vendor ~0.55. An honest vendor spreads across
    # buyers and scores ~0.11.
    vendor_n = df.groupby("vendor_id")["tender_id"].transform("count")
    pair_n = df.groupby(["vendor_id", "employee_id"])["tender_id"].transform("count")
    exclusivity = pair_n / vendor_n

    hits = df[(vendor_n >= R["concentration_min_tenders"]) &
              (exclusivity >= R["concentration_share"])].copy()
    hits["_excl"] = exclusivity[hits.index]
    return {
        row["tender_id"]: (
            f"Vendor {row['vendor_id']} gets {row['_excl']:.0%} of all its work "
            f"from buyer {row['employee_id']} alone")
        for _, row in hits.iterrows()
    }


# ═══════════════════════════════ 6. NEW VENDOR, LARGE FIRST ORDER
def rule_new_vendor_large_first_order(tenders: pd.DataFrame, vendors: pd.DataFrame) -> dict:
    """
    A vendor that shows up and immediately wins something big. Legitimate
    vendors usually build a track record; this is the pattern a shell company
    leaves instead.
    """
    df = tenders.copy()
    df["award_date"] = pd.to_datetime(df["award_date"])
    reg = vendors.set_index("vendor_id")["registration_date"]
    df["registration_date"] = pd.to_datetime(df["vendor_id"].map(reg))

    first_award = df.groupby("vendor_id")["award_date"].transform("min")
    is_first = df["award_date"] == first_award
    days_to_first = (first_award - df["registration_date"]).dt.days

    hits = df[is_first &
              (days_to_first <= R["new_vendor_max_days"]) &
              (days_to_first >= 0) &
              (df["amount"] >= R["new_vendor_min_amount"])]
    return {
        row["tender_id"]: (
            f"Vendor {row['vendor_id']} registered {int(days_to_first[row.name])} "
            f"days before winning this ${row['amount']:,.0f} award — its first ever")
        for _, row in hits.iterrows()
    }


# ═══════════════════════════════════════════════════════════ COMBINE
RULES = {
    "po_splitting":            rule_po_splitting,
    "duplicate_invoice":       rule_duplicate_invoice,
    "thin_competition":        rule_thin_competition,
    "round_near_threshold":    rule_round_near_threshold,
    "vendor_concentration":    rule_vendor_concentration,
    "new_vendor_large_first":  rule_new_vendor_large_first_order,
}


def run_all_rules(tenders: pd.DataFrame, vendors: pd.DataFrame) -> pd.DataFrame:
    """
    Runs all six rules and returns one row per tender:
        tender_id | rule_<name> (bool, x6) | n_rules_triggered | rule_score | rule_reasons
    """
    results = {}
    for name, fn in RULES.items():
        results[name] = fn(tenders, vendors) if name == "new_vendor_large_first" else fn(tenders)

    out = tenders[["tender_id"]].copy()
    for name, hit_dict in results.items():
        out[f"rule_{name}"] = out["tender_id"].isin(hit_dict.keys())

    rule_cols = [f"rule_{n}" for n in RULES]
    out["n_rules_triggered"] = out[rule_cols].sum(axis=1)
    out["rule_score"] = out["n_rules_triggered"]   # Day 4 will blend/normalize this

    def combine_reasons(tid):
        pieces = [d[tid] for d in results.values() if tid in d]
        return " | ".join(pieces)

    out["rule_reasons"] = out["tender_id"].apply(combine_reasons)
    return out
